#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.0.3
#  in conjunction with Tcl version 8.6
#    Apr 03, 2020 10:18:50 AM +07  platform: Linux
#    Apr 03, 2020 10:22:12 AM +07  platform: Linux
#    Apr 03, 2020 10:24:58 AM +07  platform: Linux
#    Apr 03, 2020 10:37:15 AM +07  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global SearchOptions
    SearchOptions = tk.IntVar()
    global BFS
    BFS = tk.IntVar()
    global IDF
    IDF = tk.IntVar()
    global LowCost
    LowCost = tk.IntVar()
    global SelectedButton
    SelectedButton = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import T
    T.vp_start_gui()





